### ISSUE TITLE
precision of objects no longer set with PARI 2.13

### ISSUE THREAD

**Issue by antonio-rojas** [sagemath/cypari2#101]
From CHANGES:

>     26- [libpari] precision0 / bitprecision0 (meant to implement GP-specific
>       commands, not for library use) are now obsolete. The new equivalent
>       commands (still not meant for library use) are precision00 and
>       bitprecision00.

`def precision` in gen.pyx needs to be updated.

**Comment by videlec** [comment]
Yep. Thanks. I noticed an issue with some doctest failures in sagemath.

**Comment by videlec** [comment]
Actually there is a `precision` function in GP that behaves differently. `cypari2` auto generates it in the correct way. I will just remove the home made implementation that used to return the precision in words.

**Comment by antonio-rojas** [comment]
I suppose this needs some adjustments on the sage side? This doesn't look right
```
sage: pari(pi).sage()
3.14159265358979323851280895940618620443274267017841339111328125000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

**Comment by videlec** [comment]
Sure, I updated a branch at https://trac.sagemath.org/ticket/30801 (still in progress)

**Comment by videlec** [comment]
I am closing this since it is a priori solved in master. Feel free to reopen if not.
