### ISSUE TITLE
Make cypari2 work with pari 2.15

### ISSUE THREAD

**Issue by tobihan** [sagemath/cypari2#122]
Several tests fail with cypari2 2.1.2 and pari 2.15. See also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1020456

    Testing cypari2.closure
    **********************************************************************
    File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10_cypari2/build/cypari2/closure.cpython-310-x86_64-linux-gnu.so", line ?, in cypari2.closure.__test__.objtoclosure (line 145)
    Failed example:
        mul([1], [2])
    Differences (ndiff with -expected +actual):
          Traceback (most recent call last):
        - ...
        - PariError: call_python: forbidden multiplication t_VEC (1 elts) * t_VEC (1 elts)
        +   File "/usr/lib/python3.10/doctest.py", line 1350, in __run
        +     exec(compile(example.source, filename, "single",
        +   File "<doctest cypari2.closure.__test__.objtoclosure (line 145)[18]>", line 1, in <module>
        +     mul([1], [2])
        +   File "cypari2/gen.pyx", line 4107, in cypari2.gen.Gen.__call__
        +     sig_on()
        +   File "cypari2/handle_error.pyx", line 213, in cypari2.handle_error._pari_err_handle
        +     raise PariError(errnum, pari_error_string, clone_gen_noclear(E))
        + PariError: call_python: incorrect type in qfbcomp (t_VEC)
    **********************************************************************
    File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10_cypari2/build/cypari2/closure.cpython-310-x86_64-linux-gnu.so", line ?, in cypari2.closure.objtoclosure
    Failed example:
        mul([1], [2])
    Differences (ndiff with -expected +actual):
          Traceback (most recent call last):
        - ...
        - PariError: call_python: forbidden multiplication t_VEC (1 elts) * t_VEC (1 elts)
        +   File "/usr/lib/python3.10/doctest.py", line 1350, in __run
        +     exec(compile(example.source, filename, "single",
        +   File "<doctest cypari2.closure.objtoclosure[18]>", line 1, in <module>
        +     mul([1], [2])
        +   File "cypari2/gen.pyx", line 4107, in cypari2.gen.Gen.__call__
        +     sig_on()
        +   File "cypari2/handle_error.pyx", line 213, in cypari2.handle_error._pari_err_handle
        +     raise PariError(errnum, pari_error_string, clone_gen_noclear(E))
        + PariError: call_python: incorrect type in qfbcomp (t_VEC)
    **********************************************************************
    2 items had failures:
       1 of  19 in cypari2.closure.__test__.objtoclosure (line 145)
       1 of  19 in cypari2.closure.objtoclosure
    ***Test Failed*** 2 failures.

Reason: PARI has merged t_QFI and t_QFR to a new type t_QFB.

    Testing cypari2.handle_error
    **********************************************************************
    File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10_cypari2/build/cypari2/handle_error.cpython-310-x86_64-linux-gnu.so", line ?, in cypari2.handle_error.__test__.PariError.__str__ (line 104)
    Failed example:
        pari('!@#$%^&*()')
    Differences (ndiff with -expected +actual):
          Traceback (most recent call last):
        - ...
        +   File "/usr/lib/python3.10/doctest.py", line 1350, in __run
        +     exec(compile(example.source, filename, "single",
        +   File "<doctest cypari2.handle_error.__test__.PariError.__str__ (line 104)[3]>", line 1, in <module>
        +     pari('!@#$%^&*()')
        +   File "cypari2/pari_instance.pyx", line 832, in cypari2.pari_instance.Pari.__call__
        +     cdef Gen g = objtogen(s)
        +   File "cypari2/gen.pyx", line 4810, in cypari2.gen.objtogen
        +     cdef GEN g = PyObject_AsGEN(s)
        +   File "cypari2/convert.pyx", line 557, in cypari2.convert.PyObject_AsGEN
        +     sig_on()
        +   File "cypari2/handle_error.pyx", line 213, in cypari2.handle_error._pari_err_handle
        +     raise PariError(errnum, pari_error_string, clone_gen_noclear(E))
        - PariError: syntax error, unexpected $undefined
        ?                                     ------   ^
        + PariError: syntax error, unexpected invalid token
        ?                                       +++++++++ ^
    **********************************************************************
    1 items had failures:
       1 of   4 in cypari2.handle_error.__test__.PariError.__str__ (line 104)
    ***Test Failed*** 1 failures.

Reason: In the Debian bug report this was attributed to a change in bison, but I'm not sure.

    Testing cypari2.pari_instance
    **********************************************************************
    File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10_cypari2/build/cypari2/pari_instance.cpython-310-x86_64-linux-gnu.so", line ?, in cypari2.pari_instance.Pari.genus2red
    Failed example:
        pari.genus2red([-5*x**5, x**3 - 2*x**2 - 2*x + 1])
    Differences (ndiff with -expected +actual):
        - [1416875, [2, -1; 5, 4; 2267, 1], x^6 - 240*x^4 - 2550*x^3 - 11400*x^2 - 24100*x - 19855, [[2, [2, [Mod(1, 2)]], []], [5, [1, []], ["[V] page 156", [3]]], [2267, [2, [Mod(432, 2267)]], ["[I{1-0-0}] page 170", []]]]]
        ?                                   ^^ ------   ^^^  ---       ^^^^^^  ^^^^^^ ^^^^^^^^^^^^
        + [1416875, [2, -1; 5, 4; 2267, 1], [-6*x^5 + 2*x^3 - x, x^3 + 1], [[2, [2, [Mod(1, 2)]], []], [5, [1, []], ["[V] page 156", [3]]], [2267, [2, [Mod(432, 2267)]], ["[I{1-0-0}] page 170", []]]]]
        ?                                   ^^    ^^^         ^^^  ^^^^ ^
    **********************************************************************
    File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10_cypari2/build/cypari2/pari_instance.cpython-310-x86_64-linux-gnu.so", line ?, in cypari2.pari_instance.Pari.genus2red
    Failed example:
        pari.genus2red([-5*x**5, x**3 - 2*x**2 - 2*x + 1],2267)
    Differences (ndiff with -expected +actual):
        - [2267, Mat([2267, 1]), x^6 - 24*x^5 + 10*x^3 - 4*x + 1, [2267, [2, [Mod(432, 2267)]], ["[I{1-0-0}] page 170", []]]]
        ?                        ^^ -----       ^^       --
        + [2267, Mat([2267, 1]), [-6*x^5 + 2*x^3 - x, x^3 + 1], [2267, [2, [Mod(432, 2267)]], ["[I{1-0-0}] page 170", []]]]
        ?                        ^^        ^        +++++    +
    **********************************************************************
    File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10_cypari2/build/cypari2/pari_instance.cpython-310-x86_64-linux-gnu.so", line ?, in cypari2.pari_instance.__test__.Pari.genus2red (line 1310)
    Failed example:
        pari.genus2red([-5*x**5, x**3 - 2*x**2 - 2*x + 1])
    Differences (ndiff with -expected +actual):
        - [1416875, [2, -1; 5, 4; 2267, 1], x^6 - 240*x^4 - 2550*x^3 - 11400*x^2 - 24100*x - 19855, [[2, [2, [Mod(1, 2)]], []], [5, [1, []], ["[V] page 156", [3]]], [2267, [2, [Mod(432, 2267)]], ["[I{1-0-0}] page 170", []]]]]
        ?                                   ^^ ------   ^^^  ---       ^^^^^^  ^^^^^^ ^^^^^^^^^^^^
        + [1416875, [2, -1; 5, 4; 2267, 1], [-6*x^5 + 2*x^3 - x, x^3 + 1], [[2, [2, [Mod(1, 2)]], []], [5, [1, []], ["[V] page 156", [3]]], [2267, [2, [Mod(432, 2267)]], ["[I{1-0-0}] page 170", []]]]]
        ?                                   ^^    ^^^         ^^^  ^^^^ ^
    **********************************************************************
    File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.10_cypari2/build/cypari2/pari_instance.cpython-310-x86_64-linux-gnu.so", line ?, in cypari2.pari_instance.__test__.Pari.genus2red (line 1310)
    Failed example:
        pari.genus2red([-5*x**5, x**3 - 2*x**2 - 2*x + 1],2267)
    Differences (ndiff with -expected +actual):
        - [2267, Mat([2267, 1]), x^6 - 24*x^5 + 10*x^3 - 4*x + 1, [2267, [2, [Mod(432, 2267)]], ["[I{1-0-0}] page 170", []]]]
        ?                        ^^ -----       ^^       --
        + [2267, Mat([2267, 1]), [-6*x^5 + 2*x^3 - x, x^3 + 1], [2267, [2, [Mod(432, 2267)]], ["[I{1-0-0}] page 170", []]]]
        ?                        ^^        ^        +++++    +
    **********************************************************************
    2 items had failures:
       2 of   5 in cypari2.pari_instance.Pari.genus2red
       2 of   5 in cypari2.pari_instance.__test__.Pari.genus2red (line 1310)
    ***Test Failed*** 4 failures.

Reason: New code for genus2red that returns a minimal model as a vector of two components instead as a single equation, which was not minimal for p=2.

**Comment by tornaria** [comment]
#123 fixes this
