### ISSUE TITLE
Incompatibility with Python 3.12

### ISSUE THREAD

**Issue by encukou** [sagemath/cypari2#137]
Python 3.12 changes the *int*ernal representation of `int` objects (to speed up common cases). Usage of `Py_SIZE` and `ob_digit` in `convert.pyx` will fail.

The supported way of extracting the value of integers (if they don't fit in a C `long long`) is the Python method [to_bytes](https://docs.python.org/3/library/stdtypes.html#int.to_bytes), and there's `from_bytes` to go back. (If this is too slow for cypari, please chime in in [the discussion](https://discuss.python.org/t/20045).)

(edit) See also: https://github.com/python/cpython/pull/101292

**Comment by tornaria** [comment]
Could we use `_PyLong_FromByteArray` and `_PyLong_AsByteArray` ?

**Comment by tornaria** [comment]
I think those will be hard to use because pari/gmp stores integers in "word little-endian" meaning `[word0, word1, word2, ...]`. This is the same as `byte little-endian` when the words themselves are little-endian. But in a big-endian architecture, there's no natural way to do it.
