### ISSUE TITLE
Release v2.1.4 on PyPI

### ISSUE THREAD

**Issue by orlitzky** [sagemath/cypari2#143]
He's still at v2.1.3: https://pypi.org/project/cypari2/

**Comment by saraedum** [comment]
This is also a problem for the release of SageMath 10.2 on conda-forge.

**Comment by saraedum** [comment]
@videlec could you release 2.1.4 or make me and or @slel maintainers?

**Comment by collares** [comment]
@saraedum It does look like you're a cypari2 maintainer on PyPI now!

**Comment by saraedum** [comment]
Thanks for the ping. Should be fixed now.

**Comment by collares** [comment]
Thank you!

**Comment by dimpase** [comment]
it seems that the tarballs on PyPI and here are not the same:
On pypi, md5 is `cf19769e37fa154cd459de6d29821a51`, but here it is `34c919aedb0a470c8b4e4b0c0ec788e3`

Any idea what happened?

**Comment by saraedum** [comment]
diff says they're identical. Probably just a timestamp difference.

**Comment by mkoeppe** [comment]
The releases on PyPI should really be done using a GH Actions workflow. 
See #141
