### ISSUE TITLE
pari headers not found on openbsd

### ISSUE THREAD

**Issue by dimpase** [sagemath/cypari2#91]
I have the following puzzling build error:
```
    [1/7] Cythonizing cypari2/closure.pyx
    [2/7] Cythonizing cypari2/convert.pyx
    [3/7] Cythonizing cypari2/gen.pyx
    [4/7] Cythonizing cypari2/handle_error.pyx
    [5/7] Cythonizing cypari2/pari_instance.pyx
    [6/7] Cythonizing cypari2/stack.pyx
    [7/7] Cythonizing cypari2/string_utils.pyx
    building 'cypari2.closure' extension
    creating build/temp.openbsd-6.6-amd64-3.7
    creating build/temp.openbsd-6.6-amd64-3.7/cypari2
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fPIC -O2 -pipe -O2 -pipe -I/usr/local/include -I/usr/local/include -fPIC -I./cypari2 -I/home/dima/sagetrac-mirror/local/lib/python3.7/site-packages/cysignals -I/home/dima/sagetrac-mirror/local/include -I/home/dima/sagetrac-mirror/local/include -I/usr/local/include/python3.7m -c cypari2/closure.c -o build/temp.openbsd-6.6-amd64-3.7/cypari2/closure.o
    cypari2/closure.c:907:3: error: type name requires a specifier or qualifier
      pari_sp (*sp)(struct __pyx_obj_7cypari2_3gen_Gen *);
      ^
...
```
and more errors showing that the build can't find definitions for `pari_sp` etc.
Where are they supposed to be? In pari headers? (Note that pari is build by Sage here).
Or are these in your generated headers?
I also surprisingly can't find cython-generated  `closure.c` anywhere - is it removed automatically after the build fails?

**Comment by videlec** [comment]
`pari_sp` is in pari headers. On my machine
```
$ grep pari_sp $(find /usr/include/pari -name "*.h") | grep typedef
/usr/include/pari/paristio.h:typedef ulong pari_sp;
```

**Comment by dimpase** [comment]
OK, thanks, but how does cypari know that this header needs to be included in cython-generated C code?

 For this seems to be the problem, a missing include.

**Comment by videlec** [comment]
`pari.h` includes everything including `paristio.h`. The `pari.h` is declared in `cypari2/types.pxd` which is included by `paridecl.pxd`.

**Comment by dimpase** [comment]
OK, it's just an old pari version installed, with its headers coming in /usr/local/include and mentioned before the correct ones in the compiler invocation. This looks like a bug (either Sage or cypari). 

One copy of -I/usr/local/include comes from my CFLAGS set to -I/usr/local/include, but the 2nd copy looks like an problem.
