### ISSUE TITLE
Needs pyproject.toml to declare build-time dependency on cysignals

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/cypari2#93]
cypari2 is affected by https://github.com/pypa/pip/issues/6193

Even though dependencies are declared in `setup.py`, by the latest pip build isolation policies, it does not install `cysignals` before doing `bdist_wheel`.

**Comment by videlec** [comment]
@mkoeppe Could you have a quick look at #104?

**Comment by mkoeppe** [comment]
Looks great to me except for the typo that I noted.
