### ISSUE TITLE
primelimit not set with PARI 2.13

### ISSUE THREAD

**Issue by antonio-rojas** [sagemath/cypari2#96]
When using PARI 2.13, the default 500000 primelimit is not correctly set when calling libpari from cypari.
```
sage: pari("default")
...
  primelimit = 0
```
The primelimit is correctly set when starting gp. Caused by upstream commit https://pari.math.u-bordeaux.fr/cgi-bin/gitweb.cgi?p=pari.git;a=commitdiff;h=a63e4b736aff004e5892819f1bbb48f15ec4c39c

**Comment by videlec** [comment]
Looks reasonable that the Python wrapper mimic the GP behavior here (ie setting `primelimit` to `maxprime`).

**Comment by videlec** [comment]
This `primelimit` attribute in `GP_DATA` is actually deprecated (file `src/headers/paristio.h` line 350). The current prime limit is given by the function `maxprime()` (not available in `GP` apparently).

**Comment by videlec** [comment]
Actually, the value is not set in `GP_DATA` but the primes table is initialized...

**Comment by videlec** [comment]
fixed in master (via #99)
